### ISSUE TITLE
Separação de cursos

### ISSUE THREAD

**Issue by jrmessias** [schoolofnetcom/transcricoes-cursos#3]
Pensando em melhor organizar as transcrições, que até então estão ocorrendo nos Cursos rápidos e Projetos práticos, já pensando em habilitar para os outros tipos de cursos/treinamentos, creio que seria bom separar as transcrições em pastas, cada um para o seu tipo de curso.

- Cursos rápidos
- Projetos práticos
- Direto ao ponto
- Carreira developer
- Live class
- Planos de estudo

Somente uma sugestão. :smile:

**Comment by wesleywillians** [comment]
Olá, pretendemos reorganizar sim todas as transcrições.
Valeu pela sugestão.

@thivalls Por favor, faz isso e informa @regina12

**Comment by thivalls** [comment]
Já comecei a organizar os cursos. 
Ótima ideia @jrmessias.

Muito obrigado mesmo.

Peço desculpas pela demora, é que estou acostumado a usar o git mais como repositório e não tinha me atentado a issue antes.

Prometo prestar mais atenção nestes pontos. Primeira vez que estou trabalhando em projetos assim com git com mais pessoas.

Obrigado

**Comment by thivalls** [comment]
Organizado por tipos.

Muito obrigado pela sugestão.
